package com.zt.demo.service;

import com.zt.demo.entity.DeUser;
import com.zt.demo.entity.DeUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeUserService {
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int countByExample(DeUserExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int deleteByExample(DeUserExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int deleteByPrimaryKey(String id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int insert(DeUser record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int insertSelective(DeUser record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    List<DeUser> selectByExample(DeUserExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    DeUser selectByPrimaryKey(String id);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int updateByExampleSelective(@Param("record") DeUser record, @Param("example") DeUserExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int updateByExample(@Param("record") DeUser record, @Param("example") DeUserExample example);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int updateByPrimaryKeySelective(DeUser record);
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    int updateByPrimaryKey(DeUser record);
}
