eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8765
spring:
  application:
    name: custom-server-feign
#启用断路器   idea不识别实则有用
feign:
  hystrix:
   enabled: true