package com.zt.demo.entity;

import lombok.Data;

@Data
public class DeUser {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.id
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.name
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.age
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.scoot
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private Integer scoot;

    private Integer eCodeRule;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column de_user.id
     *
     * @return the value of de_user.id
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column de_user.id
     *
     * @param id the value for de_user.id
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column de_user.name
     *
     * @return the value of de_user.name
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public String getname() {
        return "3333";
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column de_user.name
     *
     * @param name the value for de_user.name
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column de_user.age
     *
     * @return the value of de_user.age
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column de_user.age
     *
     * @param age the value for de_user.age
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column de_user.scoot
     *
     * @return the value of de_user.scoot
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public Integer getScoot() {
        return scoot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column de_user.scoot
     *
     * @param scoot the value for de_user.scoot
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    public void setScoot(Integer scoot) {
        this.scoot = scoot;
    }
    

}