server:
  #服务端口号
  port: 8762
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#Eureka服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
#    register-with-eureka: false
#    fetch-registry: false
spring:
  application:
    #服务名称
    name: product-server

  datasource:
    url: jdbc:mysql://localhost:3306/mysql-zt?useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: zhutong960607
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 5
    #最小连接池数量
    minIdle: 5
    #最大连接池数量
    maxActive: 20
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下#降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
    druid:
      exceptionSorter: true
      filters: stat,wall
mybatis:
    typeAliasesPackage: com.zt.demo.entity
    mapperLocations: classpath:mybatis/*.xml
