package tuling;


public class DeUser {
    
    public String getId() {
        return id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    
    public String getName() {
        return name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    
    public Integer getAge() {
        return age;
    }
    
    public void setAge(Integer age) {
        this.age = age;
    }
    
    public Integer getScoot() {
        return scoot;
    }
    
    public void setScoot(Integer scoot) {
        this.scoot = scoot;
    }
    
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.id
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.name
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.age
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private Integer age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column de_user.scoot
     *
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    private Integer scoot;

    

}