spring:
  datasource-one:
    url: jdbc:mysql://localhost:3306/study01-zt?useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: zhutong960607
    initialSize: 5
    #最小连接池数量
    minIdle: 5
    #最大连接池数量
    maxActive: 20
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下#降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
  datasource-two:
    url: jdbc:mysql://localhost:3306/study02-zt?useSSL=false&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: zhutong960607
    initialSize: 5
    #最小连接池数量
    minIdle: 5
    #最大连接池数量
    maxActive: 20
    #获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下#降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxPoolPreparedStatementPerConnectionSize: 20
    poolPreparedStatements: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    useGlobalDataSourceStat: true
#  jta:
#    log-dir: classpath:tx-logs
#    narayana:
#      transaction-manager-id: ztManager