package com.zt.demo.service.impl;

import com.zt.demo.dao.DeUserMapper;
import com.zt.demo.entity.DeUser;
import com.zt.demo.entity.DeUserExample;
import com.zt.demo.service.DeUserService;
import org.springframework.stereotype.Service;

import javax.annotation.Resource;
import java.util.List;

@Service("deUserService")
public class DeUserServiceImpl implements DeUserService {
    
    @Resource
    private DeUserMapper deUserMapper;
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param example
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int countByExample(DeUserExample example) {
        return deUserMapper.countByExample(example);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param example
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int deleteByExample(DeUserExample example) {
        return deUserMapper.deleteByExample(example);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param id
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int deleteByPrimaryKey(String id) {
        return deUserMapper.deleteByPrimaryKey(id);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param record
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int insert(DeUser record) {
        return deUserMapper.insert(record);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param record
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int insertSelective(DeUser record) {
        return deUserMapper.insertSelective(record);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param example
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public List<DeUser> selectByExample(DeUserExample example) {
        return deUserMapper.selectByExample(example);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param id
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public DeUser selectByPrimaryKey(String id) {
        return deUserMapper.selectByPrimaryKey(id);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param record
     * @param example
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int updateByExampleSelective(DeUser record, DeUserExample example) {
        return deUserMapper.updateByExampleSelective(record,example);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param record
     * @param example
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int updateByExample(DeUser record, DeUserExample example) {
        return deUserMapper.updateByExample(record,example);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param record
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int updateByPrimaryKeySelective(DeUser record) {
        return deUserMapper.updateByPrimaryKeySelective(record);
    }
    
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table de_user
     *
     * @param record
     * @mbggenerated Thu Nov 08 15:56:55 CST 2018
     */
    @Override
    public int updateByPrimaryKey(DeUser record) {
        return deUserMapper.updateByPrimaryKey(record);
    }
}
